// import { COURSE_TYPE } from "./constant.js";

const COURSE_TYPE = {
  COMPULSORY: "compulsory",
  ELECTIVE: "elective",
};

/**
 * Department wise courses list.
 * New Departments can be added here following semester courses.
 * Following courses generated using puppeteer:
 *
 */
export const CHM = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "CHM201A/CHM203A",
      code: "CHM201A/CHM203A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "Eso/So",
      code: "Eso/So-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  four: [
    {
      name: "CHM202A",
      code: "CHM202A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM222A",
      code: "CHM222A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM242A",
      code: "CHM242A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  five: [
    {
      name: "CHM303A",
      code: "CHM303A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM305A",
      code: "CHM305A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM321A",
      code: "CHM321A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM345A",
      code: "CHM345A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "CHM322A",
      code: "CHM322A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM342A",
      code: "CHM342A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM344A",
      code: "CHM344A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-1",
      code: "DE-1-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-2",
      code: "DE-2-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-2/DE",
      code: "UGP-2/DE-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "CHM423A",
      code: "CHM423A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-2",
      code: "OE-2-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3",
      code: "OE-3-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-3/DE",
      code: "UGP-3/DE-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-4",
      code: "OE-4-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-14",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-7",
      code: "OE-7-15",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const AE = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO204",
      code: "ESO204",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE201A",
      code: "AE201A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO209",
      code: "ESO209",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO202A",
      code: "MSO202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO203A",
      code: "MSO203A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO201A",
      code: "ESO201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO202A",
      code: "ESO202A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE211A",
      code: "AE211A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE251A",
      code: "AE251A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "AE311A",
      code: "AE311A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE321A",
      code: "AE321A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE331A",
      code: "AE331A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "AE341A",
      code: "AE341A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE351A",
      code: "AE351A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE361A",
      code: "AE361A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE322A",
      code: "AE322A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-2",
      code: "OE-2-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3/DE-1",
      code: "OE-3/DE-1-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "AE441A",
      code: "AE441A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE451A",
      code: "AE451A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE461A",
      code: "AE461A",
      credit: 7,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-1/OE-3",
      code: "DE-1/OE-3-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-2",
      code: "DE-2-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-2",
      code: "UGP-2",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  eight: [
    {
      name: "AE462A",
      code: "AE462A",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "AE421A",
      code: "AE421A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-4",
      code: "OE-4-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-3",
      code: "DE-3-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6/UGP-3",
      code: "OE-6/UGP-3-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const BSBE = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "BSE211A",
      code: "BSE211A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO206A",
      code: "ESO206A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  four: [
    {
      name: "BSE221A",
      code: "BSE221A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "BSE222A",
      code: "BSE222A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "BSE223A",
      code: "BSE223A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO201A",
      code: "MSO201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "BSE311A",
      code: "BSE311A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "BSE312A",
      code: "BSE312A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "Eso/So",
      code: "Eso/So-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "BSE321A",
      code: "BSE321A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "BSE322A",
      code: "BSE322A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-2",
      code: "OE-2-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-3",
      code: "OE-3-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-1/UGP-2",
      code: "DE-1/UGP-2-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "BSE411A",
      code: "BSE411A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "BSE412A",
      code: "BSE412A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-4",
      code: "OE-4-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-2/UGP-3",
      code: "DE-2/UGP-3-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "BSE421A",
      code: "BSE421A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-3",
      code: "DE-3-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-4",
      code: "DE-4-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const CHE = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "CHE251A",
      code: "CHE251A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO201",
      code: "ESO201",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO208A",
      code: "ESO208A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CSO201A/CSO202A",
      code: "CSO201A/CSO202A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE211A",
      code: "CHE211A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE221A",
      code: "CHE221A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE261A",
      code: "CHE261A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "CHE312A",
      code: "CHE312A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE313A",
      code: "CHE313A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE352A",
      code: "CHE352A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO205A",
      code: "ESO205A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-M1",
      code: "DE-M1",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "CHE331A",
      code: "CHE331A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE381A",
      code: "CHE381A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE391A",
      code: "CHE391A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-2/DE-1",
      code: "UGP-2/DE-1-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-2",
      code: "OE-2-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "CHE453A",
      code: "CHE453A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHE492A",
      code: "CHE492A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-3",
      code: "OE-3-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-3/DE-2",
      code: "UGP-3/DE-2-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-M2",
      code: "DE-M2",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  eight: [
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-5",
      code: "OE-5-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-3",
      code: "DE-3-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-4",
      code: "DE-4-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const CE = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "CE241",
      code: "CE241",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO202A",
      code: "ESO202A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO204A",
      code: "ESO204A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO203B",
      code: "MSO203B",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "CE242",
      code: "CE242",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE262A",
      code: "CE262A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE272",
      code: "CE272",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO201A",
      code: "MSO201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "CE311",
      code: "CE311",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE331A",
      code: "CE331A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE351A",
      code: "CE351A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE361A",
      code: "CE361A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE371A",
      code: "CE371A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO208A",
      code: "ESO208A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "CE325A",
      code: "CE325A",
      credit: 7,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE372A",
      code: "CE372A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE382",
      code: "CE382",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-A",
      code: "DE-A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  seven: [
    {
      name: "CE441B",
      code: "CE441B",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-A",
      code: "DE-A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-B",
      code: "DE-B",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-2",
      code: "OE-2-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3",
      code: "OE-3-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "DE-B",
      code: "DE-B",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-4",
      code: "OE-4-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-5",
      code: "OE-5-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const CSE = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "CS201A",
      code: "CS201A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CS202A",
      code: "CS202A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CS203B",
      code: "CS203B",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "ESO207A",
      code: "ESO207A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CS220A",
      code: "CS220A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CS251A",
      code: "CS251A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO201A",
      code: "MSO201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "CS330A",
      code: "CS330A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CS340A",
      code: "CS340A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CS345A",
      code: "CS345A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CS252A",
      code: "CS252A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "CS335A",
      code: "CS335A",
      credit: 13,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-2/DE-1/OE-1",
      code: "UGP-2/DE-1/OE-1-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-2",
      code: "DE-2-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-3",
      code: "DE-3-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  seven: [
    {
      name: "DE-4",
      code: "DE-4-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-3/DE-1/OE-1",
      code: "UGP-3/DE-1/OE-1-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-2",
      code: "OE-2-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3",
      code: "OE-3-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  eight: [
    {
      name: "DE-5",
      code: "DE-5-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const ES = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO213A",
      code: "ESO213A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ES311A",
      code: "ES311A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ES312A",
      code: "ES312A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ES313A",
      code: "ES313A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ES314A",
      code: "ES314A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ES315A",
      code: "ES315A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "ESO202A",
      code: "ESO202A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ES411A",
      code: "ES411A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ES412A",
      code: "ES412A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ES414A",
      code: "ES414A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-1",
      code: "DE-1-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "ES415A",
      code: "ES415A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CE361A",
      code: "CE361A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ES416A",
      code: "ES416A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-2/UGP-2",
      code: "OE-2/UGP-2-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ES413A",
      code: "ES413A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  seven: [
    {
      name: "ES417A",
      code: "ES417A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-2",
      code: "DE-2-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-3",
      code: "DE-3-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-3",
      code: "OE-3-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ES418A",
      code: "ES418A",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-4/UGP-3",
      code: "DE-4/UGP-3-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "DE-4",
      code: "DE-4-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-5",
      code: "DE-5-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-5",
      code: "OE-5-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const ECO = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "ECO201A",
      code: "ECO201A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So-2",
      code: "Eso/So-2-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "Eso/So-2",
      code: "Eso/So-2-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "Eso/So-3",
      code: "Eso/So-3-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-1",
      code: "OE-1-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ECO221A",
      code: "ECO221A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ECO261A",
      code: "ECO261A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "ECO301A",
      code: "ECO301A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ECO341A",
      code: "ECO341A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-2",
      code: "OE-2-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So-4",
      code: "Eso/So-4-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "ECO311A",
      code: "ECO311A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ECO342",
      code: "ECO342",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-1",
      code: "DE-1-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3",
      code: "OE-3-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-2/DE-2",
      code: "UGP-2/DE-2-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "ECO321A",
      code: "ECO321A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ECO411A",
      code: "ECO411A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ECO412A",
      code: "ECO412A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-3",
      code: "DE-3-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-3/OE-5",
      code: "UGP-3/OE-5-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "ECO413A",
      code: "ECO413A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-4",
      code: "DE-4-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-6",
      code: "OE-6-14",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-7",
      code: "OE-7-15",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const EE = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "EE200A",
      code: "EE200A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "MSO202A",
      code: "MSO202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO203B",
      code: "MSO203B",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "EE210A",
      code: "EE210A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "EE250A",
      code: "EE250A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO203A",
      code: "ESO203A",
      credit: 13,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO201A",
      code: "MSO201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "EE320A",
      code: "EE320A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "EE330A",
      code: "EE330A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "EE370A",
      code: "EE370A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "EE380A",
      code: "EE380A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "DE-1",
      code: "DE-1-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-2",
      code: "DE-2-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "EE340A",
      code: "EE340A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "EE381A",
      code: "EE381A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE/DE/UGP-2",
      code: "OE/DE/UGP-2-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-2",
      code: "OE-2-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3",
      code: "OE-3-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE/DE/UGP-3",
      code: "OE/DE/UGP-3-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  undefined: [
    {
      name: "DE-3",
      code: "DE-3-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-4",
      code: "DE-4-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-5",
      code: "OE-5-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const MSE = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "ESO202A",
      code: "ESO202A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO205A",
      code: "ESO205A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE201A",
      code: "MSE201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO203B",
      code: "MSO203B",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE202A",
      code: "MSE202A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE203A",
      code: "MSE203A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE204A",
      code: "MSE204A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PSO201A",
      code: "PSO201A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE301A",
      code: "MSE301A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE302A",
      code: "MSE302A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE303A",
      code: "MSE303A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE311A",
      code: "MSE311A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE313A",
      code: "MSE313A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO208A",
      code: "ESO208A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "MSE304A",
      code: "MSE304A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE305A",
      code: "MSE305A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE312A",
      code: "MSE312A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE314A",
      code: "MSE314A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSE315A",
      code: "MSE315A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-1/UGP-2",
      code: "DE-1/UGP-2-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-1",
      code: "OE-1-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "DE-2",
      code: "DE-2-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-3",
      code: "DE-3-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-2",
      code: "OE-2-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3",
      code: "OE-3-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-3/OE-5",
      code: "UGP-3/OE-5-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "DE-4",
      code: "DE-4-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-5",
      code: "DE-5-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-6",
      code: "OE-6-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-7",
      code: "OE-7-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const MTH = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "MTH201A",
      code: "MTH201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH302A",
      code: "MTH302A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "MTH204A",
      code: "MTH204A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH301A",
      code: "MTH301A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO201A",
      code: "MSO201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So",
      code: "Eso/So-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "MTH305A",
      code: "MTH305A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH403A",
      code: "MTH403A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO207A",
      code: "ESO207A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-1",
      code: "DE-1-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "MTH308B",
      code: "MTH308B",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH421A",
      code: "MTH421A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-2",
      code: "OE-2-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-2/DE/OE",
      code: "UGP-2/DE/OE-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "OE-3",
      code: "OE-3-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-2",
      code: "DE-2-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "MTH424A",
      code: "MTH424A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH430A",
      code: "MTH430A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-3/DE/OE",
      code: "UGP-3/DE/OE-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-3",
      code: "DE-3-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const ME = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO201A",
      code: "ESO201A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO209A",
      code: "ESO209A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME251A",
      code: "ME251A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO202A",
      code: "MSO202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO203B",
      code: "MSO203B",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO202A",
      code: "ESO202A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO203A",
      code: "ESO203A",
      credit: 13,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME222A",
      code: "ME222A",
      credit: 7,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME231",
      code: "ME231",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  five: [
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME301A",
      code: "ME301A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME321",
      code: "ME321",
      credit: 7,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME352A",
      code: "ME352A",
      credit: 7,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME361A",
      code: "ME361A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  six: [
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME341A",
      code: "ME341A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME351A",
      code: "ME351A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME354A",
      code: "ME354A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-2",
      code: "OE-2-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-1",
      code: "DE-1-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  seven: [
    {
      name: "HSS-5/DE-2",
      code: "HSS-5/DE-2-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ME401A",
      code: "ME401A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME451A",
      code: "ME451A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-3",
      code: "OE-3-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4/DE-3",
      code: "OE-4/DE-3-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  eight: [
    {
      name: "DE-2/HSS-5",
      code: "DE-2/HSS-5-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "ME461A",
      code: "ME461A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ME452",
      code: "ME452",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-4/DE-3",
      code: "OE-4/DE-3-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
};

export const PHY = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "PHY224A",
      code: "PHY224A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso-1",
      code: "Eso-1-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "Eso-2",
      code: "Eso-2-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "PSO201A",
      code: "PSO201A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY210A",
      code: "PHY210A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY226B",
      code: "PHY226B",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  five: [
    {
      name: "PHY315A",
      code: "PHY315A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY401A",
      code: "PHY401A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY421A",
      code: "PHY421A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY431A",
      code: "PHY431A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso-3",
      code: "Eso-3-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  six: [
    {
      name: "PHY412A",
      code: "PHY412A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY473A",
      code: "PHY473A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-1",
      code: "DE-1-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-2",
      code: "OE-2-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "PHY461A",
      code: "PHY461A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY552A",
      code: "PHY552A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-2",
      code: "DE-2-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-3/UGP-2",
      code: "OE-3/UGP-2-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  eight: [
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-3/UGP-3",
      code: "DE-3/UGP-3-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-4",
      code: "DE-4-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const SDS = {
  one: [
    {
      name: "MTH101A",
      code: "MTH101A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM101A",
      code: "CHM101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY103A",
      code: "PHY103A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC101A",
      code: "ESC101A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS",
      code: "HSS",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  two: [
    {
      name: "MTH102A",
      code: "MTH102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY101A",
      code: "PHY101A",
      credit: 3,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "PHY102A",
      code: "PHY102A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA101A",
      code: "TA101A",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "CHM102A",
      code: "CHM102A",
      credit: 8,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "LIF101A",
      code: "LIF101A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  three: [
    {
      name: "MTH301A",
      code: "MTH301A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO205A",
      code: "MSO205A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MSO202A",
      code: "MSO202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH207A",
      code: "MTH207A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH208A",
      code: "MTH208A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESC201A",
      code: "ESC201A",
      credit: 14,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA201A",
      code: "TA201A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  four: [
    {
      name: "MTH211A",
      code: "MTH211A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH210A",
      code: "MTH210A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH212A",
      code: "MTH212A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH209A",
      code: "MTH209A",
      credit: 5,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-2",
      code: "HSS-2",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "TA202A",
      code: "TA202A",
      credit: 6,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "Eso/So-3",
      code: "Eso/So-3-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  five: [
    {
      name: "MTH517A",
      code: "MTH517A",
      credit: 11,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH441A",
      code: "MTH441A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "ESO207A",
      code: "ESO207A",
      credit: 12,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "HSS-3",
      code: "HSS-3",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "OE-1",
      code: "OE-1-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-1",
      code: "UGP-1",
      credit: 4,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
  six: [
    {
      name: "MTH535A",
      code: "MTH535A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "MTH514A",
      code: "MTH514A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DC",
      code: "DC-3",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "Eso/So-5",
      code: "Eso/So-5-4",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-4",
      code: "HSS-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-2/OE-2",
      code: "UGP-2/OE-2-5",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  seven: [
    {
      name: "MTH552A",
      code: "MTH552A",
      credit: 10,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "DE-1",
      code: "DE-1-6",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-2",
      code: "DE-2-7",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "UGP-3/OE-3",
      code: "UGP-3/OE-3-8",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-4",
      code: "OE-4-9",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-5",
      code: "OE-5-10",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
  eight: [
    {
      name: "DE-3",
      code: "DE-3-11",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "DE-4",
      code: "DE-4-12",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-6",
      code: "OE-6-13",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "OE-7",
      code: "OE-7-14",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "HSS-5",
      code: "HSS-5",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
    {
      name: "UGP-4",
      code: "UGP-4",
      credit: 9,
      type: COURSE_TYPE.COMPULSORY,
    },
  ],
};

export const MTech_MSc = {
  mtech_msc: [
    {
      name: "Extra Course",
      code: "Extra Course-1",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
    {
      name: "Extra Course",
      code: "Extra Course-2",
      credit: 10,
      type: COURSE_TYPE.ELECTIVE,
    },
  ],
};
